config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'companies#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :companies, only: [:index] do
    resources :dashboards, only: [:index]
    resources :devices
    resources :device_types do
      resources :master_maintenance_plans
    end
    resources :master_maintenance_plans, only: [:index] do
      resources :tasks
    end
    resources :branches, only: [:index] do
      resources :plants, only: [:index]
    end
  end

end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_company
  before_action :authenticate_user!
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  # GET /device_types.json
  def index
    @device_types = DeviceType.all_by_company(params[:company_id])
    @device_type = DeviceType.find(params[:device_type_id]) if params[:device_type_id].present?
    @devices = Device.all_by_device_type(@device_type) if @device_type.present?
    @master_maintenance_plans = MasterMaintenancePlan.all_by_device_type(@device_type) if @device_type.present?
    if @device_type.present?
      respond_to do |format|
        format.html
        format.json
        format.js
      end
    else
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  # GET /device_types/1
  # GET /device_types/1.json
  def show
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  # POST /device_types.json
  def create
    @device_type = DeviceType.new(device_type_params)
    @device_type.company = @company

    respond_to do |format|
      if @device_type.save
        # format.html { redirect_to @device_type, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
        format.js
      else
        # format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /device_types/1
  # PATCH/PUT /device_types/1.json
  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        # format.html { redirect_to company_device_types_path, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
        format.js
      else
        # format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.json
  def destroy
    @device_type.destroy
    respond_to do |format|
      # format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_type_params
      params.require(:device_type).permit(:name)
      # params.fetch(:device_type, {})
    end
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
  # def is_active_controller(controller_name)
  #   params[:controller] == controller_name ? "active" : nil
  # end

  # def is_active_action(controller_name, action_name)
  #   (is_active_controller(controller_name) and params[:action] == action_name) ? "active" : nil
  # end
end

app/views/device_types/_detail.html.erb
<div class="ibox-title">
  <div class="m-b-md">
    <h4>
      <%= "#{t('detail_of')}: #{@device_type.try(:name)}"%>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox-content">
      <div class="ibox-title">
        <h4><%= t('devices_of_type') %></h4>
      </div>
      <div class="ibox-content">
        <%= render(
        partial: 'devices/other_devices',
        locals: { devices: @devices}
        )%>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox-content">
      <div class="ibox-title">
        <h4><%= t('master_plan_of_type') %></h4>
      </div>
      <div class="ibox-content">
        <%= render(
        partial: 'master_maintenance_plans/other_master_maintenance_plans',
        locals: { master_maintenance_plans: @master_maintenance_plans}
        )%>
      </div>
    </div>
  </div>
</div>

app/views/device_types/_details.html.erb
<div class="ibox-title">
  <div class="m-b-md">
    <h4>
      <%= "#{t('detail_of')}: #{@device_type.try(:name)}"%>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox-content">
      <div class="ibox-title">
        <div class="m-b-md">
          <%= link_to(
            "<i class='fa fa-plus-square'></i> #{t('master_plan_new')}".html_safe,
            new_company_device_type_master_maintenance_plan_path(@company, @device_type),
            class: "btn btn-primary pull-right",
            remote: true
          )%>
          <h4><%= t('master_plan_of_type') %></h4>
        </div>
      </div>
      <div id="master_plan" class="ibox-content">
        <%= render(
        partial: 'master_maintenance_plans/other_master_maintenance_plans',
        locals: { master_maintenance_plans: @master_maintenance_plans}
        )%>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="ibox-content">
      <div class="ibox-title">
        <h4><%= t('devices_of_type') %></h4>
      </div>
      <div class="ibox-content">
        <%= render(
        partial: 'devices/other_devices',
        locals: { devices: @devices}
        )%>
      </div>
    </div>
  </div>
</div>

app/views/device_types/_device_type.html.erb
<tr id='<%= "device_type-#{device_type.id}" %>'>
  <td id="name">
    <strong>
      <a href='<%= "#{company_device_types_path(@company)}?device_type_id=#{device_type.id}" %>'><%= device_type.name %></a>
    </strong>
  </td>
  <td>
    <%= link_to(
      "<i class='fa fa-edit'></i>".html_safe,
      edit_company_device_type_path(@company, device_type),
      class: "btn btn-default btn-md",
      data: { disable_with: '...' },
      remote: true
    )%>

    <%= link_to company_device_type_path(@company, device_type), class: "btn btn-default btn-md delete-device-type", 'data-delete-device-type-url':company_device_type_path(@company, device_type) do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </td>
</tr>

app/views/device_types/_form.html.erb
<%= form_for([@company, @device_type], remote: true, html: {class: "form"}) do |f| %>
  <% if @device_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_type.errors.count, "error") %> prohibited this device_type from being saved:</h2>

      <ul>
      <% @device_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label t('name') %><br />
    <%= f.text_field :name, autofocus: true, id: "name", class: "form-control" %>
  </div>

    <%= f.submit "data-disable-with": "...", class: "btn btn-primary" %>
<% end %>

app/views/device_types/create.js.erb
// $(".device_types").append(" j render @device_type ");
$('#modal-form').modal("hide");

$('#table-devices-types').DataTable().ajax.reload(null, false);
$('#detail').html("")


$(function () {
  toastr.options = notification_options
  toastr.success('Creado satisfactorimente', " " )
});

app/views/device_types/destroy.js.erb
if (<%= @device_type.errors.blank? %>) {
  $('#table-devices-types').DataTable().ajax.reload(null, false);

  $(function () {
    toastr.options = notification_options
    toastr.success('Borrado satisfactorimente', " " )
  });
} else {
  $(function () {
    toastr.options = notification_options
    toastr.error('<%= @device_type.errors.get(:base) %>', "Error" )
  });
}
$('#detail').html("")

app/views/device_types/edit.js.erb
$('#modal-title').html("<%= t('update_device_type') %>")
$('#modal-body').html("<p> <%= j render 'form' %> </p>")
$('#modal-form').modal()

app/views/device_types/index.html.erb
<% content_for :title, "PCM - #{t('devices_type')}" %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t('type_of_devices') %></h2>
    <ol class="breadcrumb">
      <%= render 'common/breadcrumb_home' %>
      <li class="active">
        <strong><%= t('type_of_devices') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div><!-- END BreadCrumb -->
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">
      <div class="ibox">
        <div class="row">
          <div class="col-lg-6">
            <div class="ibox-title">
              <div class="m-b-md">
                <%= link_to(
                  "<i class='fa fa-plus-square'></i> #{t('device_type_new')}".html_safe,
                  new_company_device_type_path(@company),
                  class: "btn btn-primary pull-right",
                  remote: true
                )%>
                <h4><%= t('type_of_devices') %></h4>
              </div>
            </div>
            <div class="ibox-content">
              <table id="table-devices-types" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <thead>
                  <tr>
                    <th><%= t('name') %></th>
                    <th></th>
                  </tr>
                </thead>
              </table>
            </div> <!-- ibox-content table -->
          </div> <!-- col-lg-6 table device types-->
            <div id="detail" class="col-lg-6">
            </div> <!-- col-lg-6 -->
        </div>
      </div> <!-- ibox -->
    </div> <!-- wrapper wrapper-content animated fadeInRight -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->

<!-- modal -->
<%= render 'common/modal' %>
<!-- end modal -->


<% content_for :javascript do %>

  <script type="text/javascript">

    $(function() {
      // DataTable
      var dta = $('#table-devices-types').DataTable({
        pageLength: 10,
        responsive: true,
        "language": lang_data_tables,

        "ajax": {
          "url": "<%= url_for :controller => params[:controller], :action => params[:action] %>"+".json"
        },

        "columns": [
          {
            data: "link",
            render: function(data, type, row) {
              return '<strong><a href="'+data.url+'?device_type_id='+data.id+'" data-remote="true">' +data.name+'</a></strong>';
            }
          },
          {
            data: "action",
            render: function(data, type, row) {
              return '<a href="'+data.edit_url+'" class="btn btn-default btn-md" data-remote="true" data-disable-with="..."><i class="fa fa-edit"></i></a>'+'<a href="'+data.destroy_url+'" id="delete-device-type" class="btn btn-default btn-md " data-delete-device-type-url="'+data.destroy_url+'"><i class="fa fa-trash-o"></i></a>';
            }
          }
        ],

        dom: '<"html5buttons"B>lTfgitp',

        buttons: [
          {extend: 'csv',
          text: "<i class='fa fa-file-text-o'></i> CSV"
          },

          {extend: 'excel',
          text: "<i class='fa fa-file-excel-o'></i> Excel",
          title: "<%= t('type_of_devices') + ' ' + @company.try(:company_name)%>"
          },

          {extend: 'pdf',
          text: "<i class='fa fa-file-pdf-o'></i> PDF",
          title: "<%= t('type_of_devices') + ' ' + @company.try(:company_name)%>",
          orientation: 'portrait'
          },

          {extend: 'print',
          text: "<i class='fa fa-print'></i>",
          title: "<%= t('type_of_devices') + ' ' + @company.try(:company_name)%>",
          customize: function (win){
            // $(win.document.body).addClass('white-bg');
            // $(win.document.body).css('font-size', '10px');

            // $(win.document.body).find('table')
            // .addClass('compact')
            // .css('font-size', 'inherit');
            }
          }
        ]
      }); // end datatables

      // Sweet Alert
      $('#table-devices-types').on("click", '#delete-device-type', function (event) {
        event.preventDefault();
        var link = $(this);
        swal(
          sweet_alert_warning,
          function () {
          var url = link.data("delete-device-type-url");
          $.ajax({
            method: "DELETE",
            dataType: "script",
            url: url
          });
        }); // end swal
      }); // end click delete-device-type
    });

  </script>

<% end %>

app/views/device_types/index.js.erb
$('#detail').html("<%= j render 'details' %>")

app/views/device_types/new.js.erb
$('#modal-title').html("<%= t('create_device_type') %>")
$('#modal-body').html("<p> <%= j render 'form' %> </p>")
$('#modal-form').modal()

app/views/device_types/update.js.erb
// $("#device_type-@device_type.id #name strong a").html(" @device_type.name ");
$('#modal-form').modal("hide")
$('#table-devices-types').DataTable().ajax.reload(null, false);
$('#detail').html("")


$(function () {
  toastr.options = notification_options
  toastr.success('Actualizado satisfactorimente', " " )
});