config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'companies#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :companies, only: [:index] do
    resources :dashboards, only: [:index]
    resources :devices
    resources :device_types do
      resources :master_maintenance_plans
    end
    resources :master_maintenance_plans, only: [:index] do
      resources :tasks
    end
    resources :branches, only: [:index] do
      resources :plants, only: [:index]
    end
  end

end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :company
  has_many :plants

  def self.all_by_company(company_id)
    Branch.joins(:company).where("companies.slug = ?", company_id).includes(:company)

  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  extend FriendlyId
  friendly_id :fantasy_name, use: :slugged

  has_many :company_users, dependent: :destroy
  has_many :users, through: :company_users
  has_many :branchs

  scope :filter_by_user, ->(user) { Company.joins(:company_users).where("company_users.users": user).order(:id)  }

end

app/models/company_user.rb
class CompanyUser < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  belongs_to :role
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :provider
  belongs_to :device_type

  belongs_to :device
  has_many :devices, dependent: :destroy

  belongs_to :system
  has_one :plant, through: :system
  has_one :branch, through: :plant
  has_one :company, through: :branch

  has_many :device_supplies
  has_many :supplies, through: :device_supplies
  has_many :instrument_types, through: :device_supplies

  has_many :device_states
  has_many :failures
  has_many :maintenance_plans

  enum electrical_start: {
    'Sin partida': 0,
    Directa: 1,
    'Estrella triángulo': 2,
    Suave: 3,
    'Variador de frecuencia': 4
  }

  enum electrical_control: {
    'Sin control': 0,
    'Interruptor automático': 1,
    Contactor: 2,
    Temporizador: 3,
    'Luz piloto': 4
  }

  def self.all_by_company(company_id)
    Device.joins(:company).where("companies.slug = ?", company_id)
  end

  def self.all_by_device_type(device_type)
    Device.where(device_type: device_type)
  end

  def supplies
    device_supplies.includes(:supply).where(lubrication: false, instrument_type_id: nil)
  end

  def lubricants
    device_supplies.includes(:supply).where(lubrication: true)
  end

  def instruments
    device_supplies.includes(:instrument_type, :supply).where.not(instrument_type_id: nil)
  end

  def other_devices_of_system
    system.devices.where.not(id: id)
  end

  def state
    "Activo"
  end
end

app/models/device_state.rb
class DeviceState < ActiveRecord::Base
  belongs_to :device

  enum state: {Activo: 0, Falla: 1}
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
  has_many :master_maintenance_plans
  belongs_to :company

  has_many :devices
  has_one :system, through: :devices
  has_one :plant, through: :system
  has_one :branch, through: :plant

  validates :company_id, presence: true
  before_destroy :check_for_devices

  def self.all_by_company(company_id)
    DeviceType.joins(:company).where("companies.slug = ?", company_id).uniq
  end

  def check_for_devices
    if devices.any?
      errors[:base] << I18n.t('cannot_delete_device_type_that_are_already_associated_devices')
      return false
    end
  end

end

app/models/failure.rb
class Failure < ActiveRecord::Base
  belongs_to :failure_type
  belongs_to :device
  has_many :maintenances
end

app/models/failure_type.rb
class FailureType < ActiveRecord::Base
  has_many :failures
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :supplies
end

app/models/maintenance.rb
class Maintenance < ActiveRecord::Base
  belongs_to :user
  belongs_to :failure
  belongs_to :provider
  belongs_to :maintenance_plan
  has_many :maintenance_supplies
  has_many :maintenance_tasks

  enum type_provider: {Interno: 0, Externo: 1}
  enum start_device_state: {Activo: 0, Falla: 1}
  #enum end_device_state: {Activo: 0, Falla: 1}
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :branch
  has_many :systems

  def self.all_by_branch(branch)
    Plant.where(branch: branch)
  end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :devices
  has_many :maintenances
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :company_users
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :item
  has_many :device_supplies
  has_many :maintenance_supplies
end

app/models/system.rb
class System < ActiveRecord::Base
  belongs_to :plant
  has_many :devices

  def self.all_by_branch(plant)
    System.where(plant: plant)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_type
  belongs_to :master_maintenance_plan
  has_many :maintenance_tasks

  validates :master_maintenance_plan_id, presence: true
  validates :task_type_id, presence: true



end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :company_users, dependent: :destroy
  has_many :companies, through: :company_users
  has_many :maintenances

  def position_by_company(company)
    company_users.find_by(company: company).try(:position)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_company
  before_action :authenticate_user!

  def index
    @branches = @company.branchs

    @branch = Branch.find(params[:branch_id]) if params[:branch_id].present?
    @plants = @branch.plants if @branch.present?

    @plant = Plant.find(params[:plant_id]) if params[:plant_id].present?
    @systems = @plant.systems if @plant

    respond_to do |format|
      format.html
      format.json
      format.js
    end

  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboards/_branches.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <% @branches.each do |branch| %>
      <div class="col-lg-3">
        <div class="contact-box center-version">
          <a href='<%= "#{company_dashboards_path(branch.company)}?branch_id=#{branch.id}" %>' data-remote="true">
            <img alt="image" class="img-circle" src="<%= image_path('sucursal-default.png') %>">
            <h3 class="m-b-xs"><strong><%= branch.name %></strong></h3>
            <address class="m-t-md">
              <%= branch.address %>
            </address>
          </a>
          <div class="contact-box-footer">
            <div class="m-t-xs btn-group">
              <a class="btn btn-xs btn-white"><i class="fa fa-edit"></i> Editar </a>
              <a class="btn btn-xs btn-white"><i class="fa fa-trash-o"></i> Eliminar </a>
            </div>
          </div> <!-- contact-box-footer -->
        </div> <!-- contact-box center-version -->
      </div> <!-- col-lg-3 -->
    <% end %>
  </div>
</div>

app/views/dashboards/_plants.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">
      <div class="ibox">
        <div class="row">
          <div class="col-lg-6">
            <div class="ibox-title">
              <div class="m-b-md">
                <!-- <%= link_to(
                  "<i class='fa fa-plus-square'></i> #{t('device_type_new')}".html_safe,
                  new_company_device_type_path(@company),
                  class: "btn btn-primary pull-right",
                  remote: true
                )%> -->
                <h4>Plantas</h4>
              </div>
            </div>
            <div class="ibox-content">
              <table id="table-plants" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th></th>
                  </tr>
                </thead>
              </table>
            </div> <!-- ibox-content table -->
          </div> <!-- col-lg-6 table device types-->
            <div id="systems" class="col-lg-6">
            </div> <!-- col-lg-6 -->
        </div>
      </div> <!-- ibox -->
    </div> <!-- wrapper wrapper-content animated fadeInRight -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->

app/views/dashboards/_systems.html.erb
<div class="ibox-title">
  <div class="m-b-md">
    <!-- <%= link_to(
      "<i class='fa fa-plus-square'></i> #{t('device_type_new')}".html_safe,
      new_company_device_type_path(@company),
      class: "btn btn-primary pull-right",
      remote: true
    )%> -->
    <h4>Sistemas</h4>
  </div>
</div>
<div class="ibox-content">
  <table id="table-systems" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Nombre</th>
        <th></th>
      </tr>
    </thead>
  </table>
</div> <!-- ibox-content table -->

app/views/dashboards/index.html.erb
<% content_for :title, "PCM - Dashboard" %>
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Dashboard</h2>
    <ol id="breadcrumb" class="breadcrumb">
      <%= render 'common/breadcrumb_home' %>
      <li id="branches">
        <strong>Sucursales</strong>
      </li>
    </ol>
  </div>
</div><!-- END BreadCrumb -->

<div id="content">
  <%= render 'branches' %>
</div>

<% content_for :javascript do %>

  <script type="text/javascript">

    $(function () {

      $('.contact-box').each(function () {
          animationHover(this, 'pulse');
      });

    });

  </script>

<% end %>

app/views/dashboards/index.js.erb
<% if (@branch.present?)  %>

  <% if (@plant.present?)  %>

    $('#branch').html("<%= @branch.name %>")
    $('#plant').html("<strong> <%= @plant.name %> </strong>")
    $('#systems').html("<%= j render 'systems' %>")

    // DataTable
    var dta2 = $('#table-systems').DataTable({
      pageLength: 10,
      responsive: true,
      "language": lang_data_tables,

      "ajax": {
        "url": "<%="#{company_dashboards_path}.json?branch_id=#{@branch.id}&plant_id=#{@plant.id}"%>"
      },

      "columns": [
        {
          data: "link",
          render: function(data, type, row) {
            return '<strong><a href="'+"<%="#{company_dashboards_path}?branch_id=#{@branch.id}&plant_id=#{@plant.id}&system_id="%>"+data.id+'" data-remote="true">' +data.name+'</a></strong>';
          }
        },
        {
          data: "action",
          render: function(data, type, row) {
            return '<a href="'+data.edit_url+'" class="btn btn-default btn-md" data-remote="true" data-disable-with="..."><i class="fa fa-edit"></i></a>'+'<a href="'+data.destroy_url+'" id="delete-plant" class="btn btn-default btn-md " data-delete-plant-url="'+data.destroy_url+'"><i class="fa fa-trash-o"></i></a>';
          }
        }
      ],

      dom: '<"html5buttons"B>lTfgitp',

      buttons: [
        {extend: 'csv',
        text: "<i class='fa fa-file-text-o'></i> CSV"
        },

        {extend: 'excel',
        text: "<i class='fa fa-file-excel-o'></i> Excel",
        title: "<%= "Sistemas  #{@company.try(:company_name)}"%>"
        },

        {extend: 'pdf',
        text: "<i class='fa fa-file-pdf-o'></i> PDF",
        title: "<%= "Sistemas  #{@company.try(:company_name)}"%>",
        orientation: 'portrait'
        },

        {extend: 'print',
        text: "<i class='fa fa-print'></i>",
        title: "<%= "Sistemas  #{@company.try(:company_name)}"%>",
        }
      ]
    }); // end datatables

  <% else %>

    $('#branches').html("<a href='<%= company_dashboards_path %>'>Sucursales</a>")
    $('#breadcrumb').append("<li id='branch'><strong> <%= @branch.name %> </strong></li><li id=plant></li>")
    $('#content').html("<%= j render 'plants' %>")

    // DataTable
    var dta = $('#table-plants').DataTable({
      pageLength: 10,
      responsive: true,
      "language": lang_data_tables,

      "ajax": {
        "url": "<%="#{company_dashboards_path}.json?branch_id=#{@branch.id}"%>"
      },

      "columns": [
        {
          data: "link",
          render: function(data, type, row) {
            return '<strong><a href="'+"<%="#{company_dashboards_path}?branch_id=#{@branch.id}&plant_id="%>"+data.id+'" data-remote="true">' +data.name+'</a></strong>';
          }
        },
        {
          data: "action",
          render: function(data, type, row) {
            return '<a href="'+data.edit_url+'" class="btn btn-default btn-md" data-remote="true" data-disable-with="..."><i class="fa fa-edit"></i></a>'+'<a href="'+data.destroy_url+'" id="delete-plant" class="btn btn-default btn-md " data-delete-plant-url="'+data.destroy_url+'"><i class="fa fa-trash-o"></i></a>';
          }
        }
      ],

      dom: '<"html5buttons"B>lTfgitp',

      buttons: [
        {extend: 'csv',
        text: "<i class='fa fa-file-text-o'></i> CSV"
        },

        {extend: 'excel',
        text: "<i class='fa fa-file-excel-o'></i> Excel",
        title: "<%= "Plantas  #{@company.try(:company_name)}"%>"
        },

        {extend: 'pdf',
        text: "<i class='fa fa-file-pdf-o'></i> PDF",
        title: "<%= "Plantas  #{@company.try(:company_name)}"%>",
        orientation: 'portrait'
        },

        {extend: 'print',
        text: "<i class='fa fa-print'></i>",
        title: "<%= "Plantas  #{@company.try(:company_name)}"%>",
        }
      ]
    }); // end datatables

  <% end %>
<% end %>