config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'companies#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :companies, only: [:index] do
    resources :dashboards, only: [:index]
    resources :devices
    resources :device_types do
      resources :master_maintenance_plans
    end
    resources :master_maintenance_plans, only: [:index] do
      resources :tasks
    end
    resources :branches, only: [:index] do
      resources :plants, only: [:index]
    end
  end

end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :company
  has_many :plants

  def self.all_by_company(company_id)
    Branch.joins(:company).where("companies.slug = ?", company_id).includes(:company)

  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  extend FriendlyId
  friendly_id :fantasy_name, use: :slugged

  has_many :company_users, dependent: :destroy
  has_many :users, through: :company_users
  has_many :branchs

  scope :filter_by_user, ->(user) { Company.joins(:company_users).where("company_users.users": user).order(:id)  }

end

app/models/company_user.rb
class CompanyUser < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  belongs_to :role
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :provider
  belongs_to :device_type

  belongs_to :device
  has_many :devices, dependent: :destroy

  belongs_to :system
  has_one :plant, through: :system
  has_one :branch, through: :plant
  has_one :company, through: :branch

  has_many :device_supplies
  has_many :supplies, through: :device_supplies
  has_many :instrument_types, through: :device_supplies

  has_many :device_states
  has_many :failures
  has_many :maintenance_plans

  enum electrical_start: {
    'Sin partida': 0,
    Directa: 1,
    'Estrella triángulo': 2,
    Suave: 3,
    'Variador de frecuencia': 4
  }

  enum electrical_control: {
    'Sin control': 0,
    'Interruptor automático': 1,
    Contactor: 2,
    Temporizador: 3,
    'Luz piloto': 4
  }

  def self.all_by_company(company_id)
    Device.joins(:company).where("companies.slug = ?", company_id)
  end

  def self.all_by_device_type(device_type)
    Device.where(device_type: device_type)
  end

  def supplies
    device_supplies.includes(:supply).where(lubrication: false, instrument_type_id: nil)
  end

  def lubricants
    device_supplies.includes(:supply).where(lubrication: true)
  end

  def instruments
    device_supplies.includes(:instrument_type, :supply).where.not(instrument_type_id: nil)
  end

  def other_devices_of_system
    system.devices.where.not(id: id)
  end

  def state
    "Activo"
  end
end

app/models/device_state.rb
class DeviceState < ActiveRecord::Base
  belongs_to :device

  enum state: {Activo: 0, Falla: 1}
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
  has_many :master_maintenance_plans
  belongs_to :company

  has_many :devices
  has_one :system, through: :devices
  has_one :plant, through: :system
  has_one :branch, through: :plant

  validates :company_id, presence: true
  before_destroy :check_for_devices

  def self.all_by_company(company_id)
    DeviceType.joins(:company).where("companies.slug = ?", company_id).uniq
  end

  def check_for_devices
    if devices.any?
      errors[:base] << I18n.t('cannot_delete_device_type_that_are_already_associated_devices')
      return false
    end
  end

end

app/models/failure.rb
class Failure < ActiveRecord::Base
  belongs_to :failure_type
  belongs_to :device
  has_many :maintenances
end

app/models/failure_type.rb
class FailureType < ActiveRecord::Base
  has_many :failures
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :supplies
end

app/models/maintenance.rb
class Maintenance < ActiveRecord::Base
  belongs_to :user
  belongs_to :failure
  belongs_to :provider
  belongs_to :maintenance_plan
  has_many :maintenance_supplies
  has_many :maintenance_tasks

  enum type_provider: {Interno: 0, Externo: 1}
  enum start_device_state: {Activo: 0, Falla: 1}
  #enum end_device_state: {Activo: 0, Falla: 1}
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :branch
  has_many :systems

  def self.all_by_branch(branch)
    Plant.where(branch: branch)
  end
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :devices
  has_many :maintenances
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :company_users
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  belongs_to :item
  has_many :device_supplies
  has_many :maintenance_supplies
end

app/models/system.rb
class System < ActiveRecord::Base
  belongs_to :plant
  has_many :devices

  def self.all_by_branch(plant)
    System.where(plant: plant)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_type
  belongs_to :master_maintenance_plan
  has_many :maintenance_tasks

  validates :master_maintenance_plan_id, presence: true
  validates :task_type_id, presence: true



end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :company_users, dependent: :destroy
  has_many :companies, through: :company_users
  has_many :maintenances

  def position_by_company(company)
    company_users.find_by(company: company).try(:position)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/common/_breadcrumb_device_index.html.erb
<li>
  <a href=
    "<%= url_for :controller => 'devices', :action => 'index' %>">
    <%= t('devices') %>
  </a>
</li>

app/views/common/_breadcrumb_device_type_index.html.erb
<li>
  <a href=
    "<%= url_for :controller => 'device_types', :action => 'index' %>">
    <%= t('type_of_devices') %>
  </a>
</li>

app/views/common/_breadcrumb_home.html.erb
<li>
  <a href="<%= root_path %>"><i class="fa fa-home"></i></a>
  <a href=""></a>
</li>

app/views/common/_modal.html.erb
<div class="modal inmodal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
              <h4 id="modal-title" class="modal-title">Modal title</h4>
              <small id="modal-description"></small>
            </div>
            <div id="modal-body" class="modal-body">

            </div>
            <div id="modal-footer" class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">
                  <%= t('close') %>
                </button>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    <%= @mainTitle %>
                </h1>
                <small>
                    <%= @mainDesc %>
                </small>
            </div>
        </div>
    </div>
</div>

app/views/home/minor.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Simple example of second view
                </h1>
                <small>Configure in home_controller.rb as minor view.</small>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        PCM Software
    </div>
    <div>
        <strong>Copyright</strong> Landes S. A. &copy; 2016-2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <span>
              <img alt="image" class="img-circle" src="<%= image_url 'user_unknown_small.gif' %>"/>
          </span>
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
            <span class="clear">
              <span class="block m-t-xs">
                <strong class="font-bold"><%= current_user.try(:name) %></strong>
              </span>
              <span class="text-muted text-xs block">
                <%= current_user.position_by_company(@company) %>
              </span>
              <span class="text-muted text-xs block">
                <%= @company.try(:fantasy_name) %> <b class="caret"></b>
              </span>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li><a href="#"><%= t('devise.shared.links.profile') %></a></li>
            <li><%= link_to t('devise.shared.links.change_company'), companies_path %></li>
            <li class="divider"></li>
            <li>
              <a href="<%= destroy_user_session_path %>" data-method="delete">
                <%= t('devise.shared.links.sign_out') %>
              </a>
            </li>
          </ul>
        </div>
        <div class="logo-element">
          PCM
        </div>
      </li> <!-- End nav header -->
      <!-- Dashboard menu -->
      <li class="<%= is_active_controller('dashboards') %>">
        <%= link_to(
          "<i class='fa fa-th-large'></i> <span class='nav-label'> Dashboard".html_safe,
          company_dashboards_path
        )%>
      </li>
      <!-- end Dashboard menu -->
      <!-- master menu -->
      <li class="<%= is_active_master %>">
        <a href="">
          <i class="fa fa-floppy-o"></i> <span class="nav-label">Maestros</span>
          <span class="fa arrow"></span>
        </a>
        <!-- Second Level of Master -->
        <ul class="nav nav-second-level collapse <%= is_active_master %>">
          <!-- list of type of devices -->
          <li class="<%= is_active_master %>">
            <%= link_to t('type_of_devices'), company_device_types_path %>
          </li>
        </ul>
      </li>
      <!-- end Master menu -->
      <!-- devices menu -->
      <li class="<%= is_active_controller('devices') %>">
        <a href="">
          <i class="fa fa-gears"></i> <span class="nav-label"><%= t('.devices') %></span>
          <span class="fa arrow"></span>
        </a>
        <!-- Second Level of Devices -->
        <ul class="nav nav-second-level collapse <%= is_active_controller('devices') %>">
          <!-- list_of_devices -->
          <li class="<%= is_active_action('devices', 'index') %>">
            <%= link_to "Todos los equipos", company_devices_path %>
          </li>
        </ul>
      </li>
      <!-- end devices menu -->
      <!-- Maintenances menu -->
      <!-- <li class="<%= is_active_controller('maintenances') %>">
        <a href="">
          <i class="fa fa-edit"></i> <span class="nav-label"><%= t('.maintenances') %></span>
          <span class="fa arrow"></span>
        </a>

        <ul class="nav nav-second-level collapse <%= is_active_controller('maintenances') %>">
          <li class="<%= nil %>">
            <%= link_to t('.list_of_maintenances'), company_devices_path %>
          </li>
          <li class="<%= nil %>">
            <%= link_to t('.list_of_maintenances'), company_devices_path %>
          </li>
        </ul>
      </li> -->
      <!-- end maitenances menu -->
    </ul>
  </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
      <!-- <form role="search" class="navbar-form-custom" method="post" action="/">
        <div class="form-group">
          <input type="text" placeholder="<%= t('.search_something') %>" class="form-control" name="top-search" id="top-search" />
        </div>
      </form> -->
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li>
        <a href="<%= destroy_user_session_path %>" data-method="delete">
          <i class="fa fa-sign-out"></i> <%= t('devise.shared.links.sign_out') %>
        </a>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/_topnavbar_show.html.erb
<div class="row border-bottom white-bg">
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <i class="fa fa-reorder"></i>
      </button>
      <a href="#" class="navbar-brand">PCM</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active">
          <a aria-expanded="false" role="button" href="<%= url_for :controller => params[:controller], :action => 'index' %>"> Volver</a>
        </li>
          <!--
        <li class="dropdown">
          <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
            <li><a href="">Menu item</a></li>
          </ul>
        </li>
         -->
      </ul>
      <ul class="nav navbar-top-links navbar-right">
        <li>
          <a href="<%= destroy_user_session_path %>" data-method="delete">
            <i class="fa fa-sign-out"></i> <%= t('devise.shared.links.sign_out') %>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="PCM is a web application, for the full management of preventive and corrective maintenances equipment within an industrial plant">
  <%= favicon_link_tag 'favicon.png' %>

  <!-- Include dinamic title -->
  <title><%= yield(:title) %></title>


  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.css") %>


  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class="skin-1">

  <!-- Wrapper-->
  <div id="wrapper">

    <!-- Navigation -->
    <%= render 'layouts/navigation' %>

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg">

      <!-- Page wrapper -->
      <%= render 'layouts/topnavbar' %>

      <!-- Main view  -->
      <%= yield %>

      <!-- Footer -->
      <%= render 'layouts/footer' %>

    </div>
    <!-- End page wrapper-->

  </div>
  <!-- End wrapper-->

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.js") %>

  <!-- Include javascript per-view -->
  <%= yield :javascript %>

</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="PCM is a web application, for the full management of preventive and corrective maintenances equipment within an industrial plant">
  <%= favicon_link_tag 'favicon.png' %>

  <!-- Include dinamic title -->
  <title><%= yield(:title) %></title>

  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.css") %>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class="gray-bg">

  <!-- Main view  -->
  <%= yield %>


  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset("#{params[:controller]}.js") %>

  <!-- Include javascript per-view -->
  <%= yield :javascript %>

</body>
</html>

app/views/layouts/layout_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="PCM is a web application, for the full management of preventive and corrective maintenances equipment within an industrial plant">
  <%= favicon_link_tag 'favicon.png' %>

  <!-- Include dinamic title -->
  <title><%= yield(:title) %></title>


  <!-- Include style per-controller - vendor plugins -->
  <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class="top-navigation">

  <!-- Wrapper-->
  <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

    <!-- Page wraper -->
    <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

      <!-- Page wrapper -->
      <%= render 'layouts/topnavbar_show' %>

      <!-- Main view  -->
      <%= yield %>

      <!-- Footer -->
      <%= render 'layouts/footer' %>

    </div>
    <!-- End page wrapper-->

  </div>
  <!-- End wrapper-->

  <!-- Include javascript per-controller - vendor plugins -->
  <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

  <!-- Include javascript per-view -->
  <%= yield :javascript %>

</body>
</html>